version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - prealloc
    - revive
    - sloglint
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    cyclop:
      max-complexity: 30
      package-average: 10
    errcheck:
      check-type-assertions: true
    funlen:
      lines: 100
      statements: 50
      ignore-comments: true
    gocognit:
      min-complexity: 20
    gocyclo:
      min-complexity: 20
    gosec:
      severity: medium
      confidence: medium
      config:
        G301: "0750"
        G302: "0640"
        G306: "0640"
    misspell:
      locale: US
      extra-words:
        - typo: artefact
          correction: artifact
    revive:
      enable-all-rules: false
      rules:
        - name: add-constant
          arguments:
            - allowFloats: 0.0,0.,1.0,1.,2.0,2.,3.0,3.,4.0,4.,5.0,5.,6.0,6.,7.0,7.,8.0,8.,9.0,9.
              allowInts: 0,1,2,3,4,5,6,7,8,9,10,0o755,0o644
              allowStrs: '"","\n"'
              ignoreFuncs: fmt\.*,slog\.*,.*\.WriteString
              maxLitCount: "5"
          severity: warning
        - name: argument-limit
          arguments:
            - 5
          severity: warning
        - name: atomic
        - name: bool-literal-in-expr
          severity: warning
        - name: confusing-naming
          severity: warning
        - name: confusing-results
        - name: constant-logical-expr
          severity: warning
        - name: context-keys-type
        - name: datarace
        - name: deep-exit
          severity: warning
        - name: defer
          arguments:
            - - immediate-recover
              - recover
              - return
              - loop
        - name: dot-imports
          severity: warning
        - name: duplicated-imports
        - name: early-return
          severity: warning
        - name: errorf
        - name: exported
          arguments:
            - checkPublicInterface
        - name: filename-format
        - name: flag-parameter
          severity: warning
        - name: get-return
        - name: identical-branches
        - name: if-return
        - name: import-shadowing
          severity: warning
        - name: increment-decrement
        - name: indent-error-flow
        - name: nested-structs
          severity: warning
        - name: optimize-operands-order
        - name: range
        - name: redefines-builtin-id
        - name: redundant-import-alias
        - name: string-of-int
        - name: struct-tag
          arguments:
            - json,inline
        - name: superfluous-else
        - name: time-equal
        - name: time-naming
        - name: unchecked-type-assertion
        - name: unconditional-recursion
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: unused-parameter
        - name: use-any
        - name: useless-break
        - name: var-declaration
        - name: waitgroup-by-value
    sloglint:
      no-mixed-args: true
      no-global: all
      context: scope
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - cyclop
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
severity:
  default: error
  rules:
    - linters:
        - cyclop
        - funlen
        - gocognit
        - gocyclo
      severity: info
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
