package xstrings

import (
	"testing"

	"github.com/neticdk/go-stdlib/assert"
)

func TestSlugifyDefaultOptions(t *testing.T) {
	tests := []struct {
		name          string
		input         string
		expected      string
		lowercase     bool
		decamelize    bool
		transliterate bool
	}{
		{
			name:          "empty_all_true",
			input:         "",
			expected:      "",
			lowercase:     true,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "empty_all_true_except_transliterate",
			input:         "",
			expected:      "",
			lowercase:     true,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "empty_all_false_except_lowercase",
			input:         "",
			expected:      "",
			lowercase:     true,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "empty_all_false_except_transliterate",
			input:         "",
			expected:      "",
			lowercase:     true,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "empty_all_false",
			input:         "",
			expected:      "",
			lowercase:     false,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "empty_all_false_except_transliterate",
			input:         "",
			expected:      "",
			lowercase:     false,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "empty_all_false_except_decamelize_and_transliterate",
			input:         "",
			expected:      "",
			lowercase:     false,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "empty_all_false_except_decamelize",
			input:         "",
			expected:      "",
			lowercase:     false,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "hello_world_all_true",
			input:         "hello world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "hello_world_all_true_except_transliterate",
			input:         "hello world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "hello_world_all_false_except_lowercase",
			input:         "hello world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "hello_world_all_false_except_transliterate",
			input:         "hello world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "hello_world_all_false",
			input:         "hello world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "hello_world_all_false_except_transliterate",
			input:         "hello world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "hello_world_all_false_except_decamelize_and_transliterate",
			input:         "hello world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "hello_world_all_false_except_decamelize",
			input:         "hello world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "hello_double_space_all_true",
			input:         "hello  world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "hello_double_space_all_true_except_transliterate",
			input:         "hello  world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "hello_double_space_all_false_except_lowercase",
			input:         "hello  world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "hello_double_space_all_false_except_transliterate",
			input:         "hello  world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "hello_double_space_all_false",
			input:         "hello  world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "hello_double_space_all_false_except_transliterate",
			input:         "hello  world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "hello_double_space_all_false_except_decamelize_and_transliterate",
			input:         "hello  world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "hello_double_space_all_false_except_decamelize",
			input:         "hello  world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "hello_triple_dash_all_true",
			input:         "hello---world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "hello_triple_dash_all_true_except_transliterate",
			input:         "hello---world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "hello_triple_dash_all_false_except_lowercase",
			input:         "hello---world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "hello_triple_dash_all_false_except_transliterate",
			input:         "hello---world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "hello_triple_dash_all_false",
			input:         "hello---world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "hello_triple_dash_all_false_except_transliterate",
			input:         "hello---world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "hello_triple_dash_all_false_except_decamelize_and_transliterate",
			input:         "hello---world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "hello_triple_dash_all_false_except_decamelize",
			input:         "hello---world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "hello_space_dash_space_all_true",
			input:         "hello- -world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "hello_space_dash_space_all_true_except_transliterate",
			input:         "hello- -world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "hello_space_dash_space_all_false_except_lowercase",
			input:         "hello- -world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "hello_space_dash_space_all_false_except_transliterate",
			input:         "hello- -world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "hello_space_dash_space_all_false",
			input:         "hello- -world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "hello_space_dash_space_all_false_except_transliterate",
			input:         "hello- -world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "hello_space_dash_space_all_false_except_decamelize_and_transliterate",
			input:         "hello- -world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "hello_space_dash_space_all_false_except_decamelize",
			input:         "hello- -world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "hello_space_dash_space_all_true",
			input:         "hello - - world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "hello_space_dash_space_all_true_except_transliterate",
			input:         "hello - - world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "hello_space_dash_space_all_false_except_lowercase",
			input:         "hello - - world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "hello_space_dash_space_all_false_except_transliterate",
			input:         "hello - - world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "hello_space_dash_space_all_false",
			input:         "hello - - world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "hello_space_dash_space_all_false_except_transliterate",
			input:         "hello - - world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "hello_space_dash_space_all_false_except_decamelize_and_transliterate",
			input:         "hello - - world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "hello_space_dash_space_all_false_except_decamelize",
			input:         "hello - - world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "dashes_all_true",
			input:         "-------",
			expected:      "",
			lowercase:     true,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "dashes_all_true_except_transliterate",
			input:         "-------",
			expected:      "",
			lowercase:     true,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "dashes_all_false_except_lowercase",
			input:         "-------",
			expected:      "",
			lowercase:     true,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "dashes_all_false_except_transliterate",
			input:         "-------",
			expected:      "",
			lowercase:     true,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "dashes_all_false",
			input:         "-------",
			expected:      "",
			lowercase:     false,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "dashes_all_false_except_transliterate",
			input:         "-------",
			expected:      "",
			lowercase:     false,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "dashes_all_false_except_decamelize_and_transliterate",
			input:         "-------",
			expected:      "",
			lowercase:     false,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "dashes_all_false_except_decamelize",
			input:         "-------",
			expected:      "",
			lowercase:     false,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "dash_hello_world_all_true",
			input:         "-hello world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "dash_hello_world_all_true_except_transliterate",
			input:         "-hello world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "dash_hello_world_all_false_except_lowercase",
			input:         "-hello world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "dash_hello_world_all_false_except_transliterate",
			input:         "-hello world",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "dash_hello_world_all_false",
			input:         "-hello world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "dash_hello_world_all_false_except_transliterate",
			input:         "-hello world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "dash_hello_world_all_false_except_decamelize_and_transliterate",
			input:         "-hello world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "dash_hello_world_all_false_except_decamelize",
			input:         "-hello world",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "space_hello_world_space_all_true",
			input:         " hello world ",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "space_hello_world_space_all_true_except_transliterate",
			input:         " hello world ",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "space_hello_world_space_all_false_except_lowercase",
			input:         " hello world ",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "space_hello_world_space_all_false_except_transliterate",
			input:         " hello world ",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "space_hello_world_space_all_false",
			input:         " hello world ",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "space_hello_world_space_all_false_except_transliterate",
			input:         " hello world ",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "space_hello_world_space_all_false_except_decamelize_and_transliterate",
			input:         " hello world ",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "space_hello_world_space_all_false_except_decamelize",
			input:         " hello world ",
			expected:      "hello-world",
			lowercase:     false,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "special_characters_all_true",
			input:         "!@#$%^&*()_+=-`~[]\\{}|;':\",./<>?",
			expected:      "",
			lowercase:     true,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "special_characters_all_true_except_transliterate",
			input:         "!@#$%^&*()_+=-`~[]\\{}|;':\",./<>?",
			expected:      "",
			lowercase:     true,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "special_characters_all_false_except_lowercase",
			input:         "!@#$%^&*()_+=-`~[]\\{}|;':\",./<>?",
			expected:      "",
			lowercase:     true,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "special_characters_all_false_except_transliterate",
			input:         "!@#$%^&*()_+=-`~[]\\{}|;':\",./<>?",
			expected:      "",
			lowercase:     true,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "special_characters_all_false",
			input:         "!@#$%^&*()_+=-`~[]\\{}|;':\",./<>?",
			expected:      "",
			lowercase:     false,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "special_characters_all_false_except_transliterate",
			input:         "!@#$%^&*()_+=-`~[]\\{}|;':\",./<>?",
			expected:      "",
			lowercase:     false,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "special_characters_all_false_except_decamelize_and_transliterate",
			input:         "!@#$%^&*()_+=-`~[]\\{}|;':\",./<>?",
			expected:      "",
			lowercase:     false,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "special_characters_all_false_except_decamelize",
			input:         "!@#$%^&*()_+=-`~[]\\{}|;':\",./<>?",
			expected:      "",
			lowercase:     false,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "unicode_all_true",
			input:         "HélLø Wörld",
			expected:      "hel-lo-world",
			lowercase:     true,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "unicode_all_true_except_transliterate",
			input:         "HélLø Wörld",
			expected:      "h-l-l-w-rld",
			lowercase:     true,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "unicode_all_false_except_lowercase",
			input:         "HélLø Wörld",
			expected:      "h-ll-w-rld",
			lowercase:     true,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "unicode_all_false_except_transliterate",
			input:         "HélLø Wörld",
			expected:      "hello-world",
			lowercase:     true,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "unicode_all_false",
			input:         "HélLø Wörld",
			expected:      "H-lL-W-rld",
			lowercase:     false,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "unicode_all_false_except_transliterate",
			input:         "HélLø Wörld",
			expected:      "HelLo-World",
			lowercase:     false,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "unicode_all_false_except_decamelize_and_transliterate",
			input:         "HélLø Wörld",
			expected:      "hel-lo-world",
			lowercase:     false,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "unicode_all_false_except_decamelize",
			input:         "HélLø Wörld",
			expected:      "h-l-l-w-rld",
			lowercase:     false,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "dots_all_true",
			input:         "with.dots.everywhere",
			expected:      "with-dots-everywhere",
			lowercase:     true,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "dots_all_true_except_transliterate",
			input:         "with.dots.everywhere",
			expected:      "with-dots-everywhere",
			lowercase:     true,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "dots_all_false_except_lowercase",
			input:         "with.dots.everywhere",
			expected:      "with-dots-everywhere",
			lowercase:     true,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "dots_all_false_except_transliterate",
			input:         "with.dots.everywhere",
			expected:      "with-dots-everywhere",
			lowercase:     true,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "dots_all_false",
			input:         "with.dots.everywhere",
			expected:      "with-dots-everywhere",
			lowercase:     false,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "dots_all_false_except_transliterate",
			input:         "with.dots.everywhere",
			expected:      "with-dots-everywhere",
			lowercase:     false,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "dots_all_false_except_decamelize_and_transliterate",
			input:         "with.dots.everywhere",
			expected:      "with-dots-everywhere",
			lowercase:     false,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "dots_all_false_except_decamelize",
			input:         "with.dots.everywhere",
			expected:      "with-dots-everywhere",
			lowercase:     false,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "numbers_all_true",
			input:         "12345",
			expected:      "12345",
			lowercase:     true,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "numbers_all_true_except_transliterate",
			input:         "12345",
			expected:      "12345",
			lowercase:     true,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "numbers_all_false_except_lowercase",
			input:         "12345",
			expected:      "12345",
			lowercase:     true,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "numbers_all_false_except_transliterate",
			input:         "12345",
			expected:      "12345",
			lowercase:     true,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "numbers_all_false",
			input:         "12345",
			expected:      "12345",
			lowercase:     false,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "numbers_all_false_except_transliterate",
			input:         "12345",
			expected:      "12345",
			lowercase:     false,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "numbers_all_false_except_decamelize_and_transliterate",
			input:         "12345",
			expected:      "12345",
			lowercase:     false,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "numbers_all_false_except_decamelize",
			input:         "12345",
			expected:      "12345",
			lowercase:     false,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "mixed_case_all_true",
			input:         "MixedCase123",
			expected:      "mixed-case-123",
			lowercase:     true,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "mixed_case_all_true_except_transliterate",
			input:         "MixedCase123",
			expected:      "mixed-case-123",
			lowercase:     true,
			decamelize:    true,
			transliterate: false,
		},
		{
			name:          "mixed_case_all_false_except_lowercase",
			input:         "MixedCase123",
			expected:      "mixedcase123",
			lowercase:     true,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "mixed_case_all_false_except_transliterate",
			input:         "MixedCase123",
			expected:      "mixedcase123",
			lowercase:     true,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "mixed_case_all_false",
			input:         "MixedCase123",
			expected:      "MixedCase123",
			lowercase:     false,
			decamelize:    false,
			transliterate: false,
		},
		{
			name:          "mixed_case_all_false_except_transliterate",
			input:         "MixedCase123",
			expected:      "MixedCase123",
			lowercase:     false,
			decamelize:    false,
			transliterate: true,
		},
		{
			name:          "mixed_case_all_false_except_decamelize_and_transliterate",
			input:         "MixedCase123",
			expected:      "mixed-case-123",
			lowercase:     false,
			decamelize:    true,
			transliterate: true,
		},
		{
			name:          "mixed_case_all_false_except_decamelize",
			input:         "MixedCase123",
			expected:      "mixed-case-123",
			lowercase:     false,
			decamelize:    true,
			transliterate: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			actual := Slugify(
				tt.input,
				WithDecamelize(tt.decamelize),
				WithLowercase(tt.lowercase),
				WithTransliterate(tt.transliterate),
			)
			assert.Equal(t, actual, tt.expected, "Slugify/%q", tt.name)
		})
	}
}
