// Package table contains the generated transliteration data for the
// transliterate package.
package table

// Tables maps a rune's high byte (section) to a slice of strings representing
// the transliterations for the 256 code points within that section.
// The index into the []string corresponds to the rune's low byte.
// This map is populated lazily by the transliterate package.
var Tables = map[rune][]string{}

// Note: The individual table slices (X000, X001, etc.) are in separate xNNN.go files,
// generated by make_table.go.
